### ISSUE TITLE
RFC: Better image format/typing

### ISSUE THREAD

**Issue by MinhxNguyen7** [uci-uav-forge/uavf_2024#34]
Right now, it's pretty unclear what the shape of an image is, whether it's `(height, width, channels)`, `(channels, height, width)`, or something else. We seem undecided on what it should be, and there's disagreement between the code, the models, and our documentation.

Instead of passing around `ndarray` images, there can be a class that also states the shape of the image and that can be converted to another shape as needed. 

Example usage:
```python
#### imaging_tpyes.py
class Image:
    ...

class ImageDimension(Enum):
    HEIGHT = 'h'
    WIDTH = 'w'
    CHANNELS = 'c'

HEIGHT = ImageDimension.HEIGHT
WIDTH = ImageDimension.WIDTH
CHANNELS = ImageDimension.CHANNELS

### usage
img: Image[HEIGHT, WIDTH, CHANNELS] = Image(img_array)
img_for_other_use = img.change_shape((CHANNELS, HEIGHT, WIDTH))
def some_func(img: Image[CHANNELS, HEIGHT, WIDTH]):
    ...
    
some_func(img) # IDE will complain
some_func(img_for_other_use) # OK
```
This approach shouldn't break anything in runtime when the type hinting is incorrect, but the IDE will give you error squiggles.

@EricPedley @Vince-C156 Let me know what you guys think

**Comment by EricPedley** [comment]
Sounds good to me
